name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - defaults
dependencies:
  - openssh=10.2p1
  - python=3.12
  - coverage
  - ruff
  - python-dotenv>=0.5.1
  - pre_commit
  - cookiecutter
  - questionary
  - air==0.9.0
